/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/BLfzwAdmmno
 */
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import userStore from "@/lib/userStore";

export default function RecipeCard2() {
  const { drinkImage, drinkRecipe } = userStore();

  return (
    <Card className="w-full max-w-md">
      <CardHeader className="px-6 pt-6 pb-4">
        <CardTitle className="text-3xl font-bold">{drinkRecipe.name}</CardTitle>
        <CardDescription>
          A classic Cuban cocktail with a refreshing blend of rum, lime juice,
          mint leaves, and soda water.
        </CardDescription>
      </CardHeader>
      <CardContent className="bg-gray-100 py-6 flex items-center justify-center gap-6 dark:bg-gray-800">
        <img
          alt="Mojito cocktail"
          className="rounded-xl object-cover"
          height="400"
          src="/placeholder.svg"
          style={{
            aspectRatio: "1200/400",
            objectFit: "cover",
          }}
          width="1200"
        />
      </CardContent>
      <CardContent className="">
        <div className="items-center gap-4">
          <h3 className="text-sm font-semibold mb-1">Preparation</h3>
          <ul className="pl-2 text-sm">
            {drinkRecipe.ingredients
              .filter((item) => item.name !== "Ice cubes")
              .map((ingredient, index) => (
                <li key={index}>
                  {ingredient.quantity} {ingredient.name.toLowerCase()}
                </li>
              ))}
          </ul>
        </div>
      </CardContent>
      <CardContent className="">
        <div className="">
          <h3 className="text-sm font-semibold mb-1">Preparation</h3>
          <ol className="list-decimal pl-6 text-sm">
            {drinkRecipe.instructions.split(".").map((step, index) => (
              <li key={index}>{step}</li>
            ))}
          </ol>
        </div>
      </CardContent>
      <CardFooter className="flex justify-end gap-2">
        <Button>Start Over</Button>
      </CardFooter>
    </Card>
  );
}
