/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/7bs2BdoeQ5Q
 */

"use client";
import { Button } from "@/components/ui/button";
import {
  DropdownMenuTrigger,
  DropdownMenuRadioItem,
  DropdownMenuRadioGroup,
  DropdownMenuContent,
  DropdownMenu,
} from "@/components/ui/dropdown-menu";
import { useState } from "react";

export default function Dropdown() {
  const [position, setPosition] = useState("sour");

  return (
    <section className="w-full py-12 md:py-24">
      <div className="container px-4 md:px-6 flex flex-col gap-4">
        <div className="flex flex-col gap-2 items-center justify-center text-center">
          <div className="grid gap-1">
            <h1 className="text-3xl font-bold tracking-tight">
              Cocktail Recipe Generator
            </h1>
            <p className="text-gray-500 dark:text-gray-400">
              Let's mix up something special! Select your preferences and we'll
              give you a unique cocktail recipe.
            </p>
          </div>
        </div>
        <div className="flex flex-col gap-4">
          <div className="flex flex-row gap-10 justify-center">
            {" "}
            <DropdownMenu className="">
              <DropdownMenuTrigger asChild>
                <Button className="w-[150px]" variant="outline">
                  Flavor Profile
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent className="min-w-[150px]">
                <DropdownMenuRadioGroup
                  value={position}
                  onValueChange={setPosition}
                >
                  <DropdownMenuRadioItem value="sweet">
                    Sweet
                  </DropdownMenuRadioItem>
                  <DropdownMenuRadioItem value="sour">
                    Sour
                  </DropdownMenuRadioItem>
                  <DropdownMenuRadioItem value="bitter">
                    Bitter
                  </DropdownMenuRadioItem>
                  <DropdownMenuRadioItem value="fruity">
                    Fruity
                  </DropdownMenuRadioItem>
                </DropdownMenuRadioGroup>
              </DropdownMenuContent>
            </DropdownMenu>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button className="w-[150px]" variant="outline">
                  Liquor
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent className="min-w-[150px]">
                <DropdownMenuRadioGroup value="vodka">
                  <DropdownMenuRadioItem value="vodka">
                    Vodka
                  </DropdownMenuRadioItem>
                  <DropdownMenuRadioItem value="rum">Rum</DropdownMenuRadioItem>
                  <DropdownMenuRadioItem value="gin">Gin</DropdownMenuRadioItem>
                  <DropdownMenuRadioItem value="tequila">
                    Tequila
                  </DropdownMenuRadioItem>
                </DropdownMenuRadioGroup>
              </DropdownMenuContent>
            </DropdownMenu>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button className="w-[150px]" variant="outline">
                  Mood
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent className="min-w-[150px]">
                <DropdownMenuRadioGroup value="refreshing">
                  <DropdownMenuRadioItem value="refreshing">
                    Refreshing
                  </DropdownMenuRadioItem>
                  <DropdownMenuRadioItem value="relaxing">
                    Relaxing
                  </DropdownMenuRadioItem>
                  <DropdownMenuRadioItem value="energizing">
                    Energizing
                  </DropdownMenuRadioItem>
                </DropdownMenuRadioGroup>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
          <Button className="mx-auto w-full md:w-auto max-w-xs">
            Generate Recipe
          </Button>
        </div>
      </div>
    </section>
  );
}
