/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/oVjDprhsT4r
 */
import { CardTitle, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"

export function RecipeCard2() {
  return (
    (<Card className="w-full max-w-lg">
      <CardHeader>
        <CardTitle>Classic Mojito</CardTitle>
      </CardHeader>
      <CardContent className="grid gap-4">
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 rounded-full overflow-hidden">
            <img
              alt="Mojito"
              height="64"
              src="/placeholder.svg"
              style={{
                aspectRatio: "64/64",
                objectFit: "cover",
              }}
              width="64" />
          </div>
          <ul className="grid gap-2 text-sm">
            <li>2 oz white rum</li>
            <li>1 oz fresh lime juice</li>
            <li>1 oz simple syrup</li>
            <li>6-8 fresh mint leaves</li>
            <li>Club soda</li>
          </ul>
        </div>
        <div>
          <h3 className="text-sm font-medium mb-1">Preparation</h3>
          <ol className="list-decimal pl-6 text-sm">
            <li>In a glass, muddle the mint leaves with lime juice and simple syrup.</li>
            <li>Fill the glass with ice cubes.</li>
            <li>Add white rum and stir well.</li>
            <li>Top it off with club soda.</li>
            <li>Garnish with mint leaves and lime slices.</li>
          </ol>
        </div>
      </CardContent>
      <CardFooter>
        <p className="text-sm">Enjoy responsibly. Drink responsibly.</p>
      </CardFooter>
    </Card>)
  );
}
