/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/BLfzwAdmmno
 */
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function Recipe() {
  return (
    (<Card className="w-full max-w-md">
      <CardHeader className="px-6 pt-6 pb-4">
        <CardTitle className="text-3xl font-bold">Mojito</CardTitle>
        <CardDescription>
          A classic Cuban cocktail with a refreshing blend of rum, lime juice, mint leaves, and soda water.
        </CardDescription>
      </CardHeader>
      <CardContent
        className="bg-gray-100 py-6 flex items-center justify-center gap-6 dark:bg-gray-800">
        <img
          alt="Mojito cocktail"
          className="rounded-xl object-cover"
          height="400"
          src="/placeholder.svg"
          style={{
            aspectRatio: "1200/400",
            objectFit: "cover",
          }}
          width="1200" />
      </CardContent>
      <CardContent className="grid gap-2 border-t py-6">
        <dl className="grid grid-cols-2 text-sm gap-x-4">
          <div>White rum</div>
          <div>Lime juice</div>
          <div>Mint leaves</div>
          <div>Simple syrup</div>
          <div>Soda water</div>
          <div>Ice cubes</div>
        </dl>
      </CardContent>
      <CardContent className="grid gap-4 py-6">
        <ol className="list-decimal pl-6 text-sm grid gap-2">
          <li>Muddle mint leaves and lime juice in a glass.</li>
          <li>Add simple syrup and white rum.</li>
          <li>Fill the glass with ice cubes.</li>
          <li>Top it off with soda water.</li>
          <li>Stir gently to combine.</li>
        </ol>
      </CardContent>
      <CardFooter className="flex justify-end gap-2">
        <Button variant="outline">Edit</Button>
        <Button>Save</Button>
      </CardFooter>
    </Card>)
  );
}
